/*
	
	***************************************************
	*												  *
	*       PreRequisite Name - LegacyIndex			  *
	*												  *
	***************************************************
   
   Purpose : To Create Indexes in Legacy Database

 */


IF EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[GAM].[ASSET_STANDARD_DETAILS]') AND name = N'INDX_STD_DTL_UID')
DROP INDEX INDX_STD_DTL_UID ON [GAM].[ASSET_STANDARD_DETAILS]
GO

CREATE NONCLUSTERED INDEX [INDX_STD_DTL_UID]
ON [GAM].[ASSET_STANDARD_DETAILS] ([ASD_AM_UID],[ASD_CLST_STAT_ID])
INCLUDE ([ASD_STD_ID])
GO


IF EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[GAM].[ASSET_TRANSFER_LIST]') AND name = N'INDX_AST_LIST')
DROP INDEX INDX_AST_LIST ON [GAM].[ASSET_TRANSFER_LIST]
GO

CREATE NONCLUSTERED INDEX [INDX_AST_LIST]
ON [GAM].[ASSET_TRANSFER_LIST] ([ASTL_CLST_ID])
INCLUDE ([ASTL_DATA_SOURCE])
GO


IF EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[GAM].[TYPE_CODE_VALUES]') AND name = N'INDX_TYP_CD_VALUES')
DROP INDEX INDX_TYP_CD_VALUES ON [GAM].[TYPE_CODE_VALUES]
GO

CREATE NONCLUSTERED INDEX [INDX_TYP_CD_VALUES]
ON [GAM].[TYPE_CODE_VALUES] ([TYCV_TYCOD_ID],[TYCV_OPTN_ID])
INCLUDE ([TYCV_ID],[TYCV_OPTN_VALUE])
GO

IF EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[PROGRESSIVE].[SLOT]') AND name = N'INDX_SLOT_ID')
DROP INDEX INDX_SLOT_ID ON [PROGRESSIVE].[SLOT]
GO

CREATE NONCLUSTERED INDEX [INDX_SLOT_ID]
ON [PROGRESSIVE].[SLOT] ([ASD_STD_ID])

IF EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[GAM].[ASSET_STANDARD_DETAILS]') AND name = N'INDX_STD_DTL_MAP_UID')
DROP INDEX INDX_STD_DTL_MAP_UID ON [GAM].[ASSET_STANDARD_DETAILS]
GO

CREATE NONCLUSTERED INDEX [INDX_STD_DTL_MAP_UID]
ON [GAM].[ASSET_STANDARD_DETAILS] ([ASD_AM_UID])
INCLUDE ([ASD_ASST_ID],[ASD_INSMAP_ID])

GO
